function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

export namespace Flag {
  export const PROJECTFLOWS_AUTO_SHARE = truthy("PROJECTFLOWS_AUTO_SHARE")
  export const PROJECTFLOWS_GIT_BASH_PATH = process.env["PROJECTFLOWS_GIT_BASH_PATH"]
  export const PROJECTFLOWS_CONFIG = process.env["PROJECTFLOWS_CONFIG"]
  export declare const PROJECTFLOWS_TUI_CONFIG: string | undefined
  export declare const PROJECTFLOWS_CONFIG_DIR: string | undefined
  export const PROJECTFLOWS_CONFIG_CONTENT = process.env["PROJECTFLOWS_CONFIG_CONTENT"]
  export const PROJECTFLOWS_DISABLE_AUTOUPDATE = truthy("PROJECTFLOWS_DISABLE_AUTOUPDATE")
  export const PROJECTFLOWS_DISABLE_PRUNE = truthy("PROJECTFLOWS_DISABLE_PRUNE")
  export const PROJECTFLOWS_DISABLE_TERMINAL_TITLE = truthy("PROJECTFLOWS_DISABLE_TERMINAL_TITLE")
  export const PROJECTFLOWS_PERMISSION = process.env["PROJECTFLOWS_PERMISSION"]
  export const PROJECTFLOWS_DISABLE_DEFAULT_PLUGINS = truthy("PROJECTFLOWS_DISABLE_DEFAULT_PLUGINS")
  export const PROJECTFLOWS_DISABLE_LSP_DOWNLOAD = truthy("PROJECTFLOWS_DISABLE_LSP_DOWNLOAD")
  export const PROJECTFLOWS_ENABLE_EXPERIMENTAL_MODELS = truthy("PROJECTFLOWS_ENABLE_EXPERIMENTAL_MODELS")
  export const PROJECTFLOWS_DISABLE_AUTOCOMPACT = truthy("PROJECTFLOWS_DISABLE_AUTOCOMPACT")
  export const PROJECTFLOWS_DISABLE_MODELS_FETCH = truthy("PROJECTFLOWS_DISABLE_MODELS_FETCH")
  export const PROJECTFLOWS_DISABLE_CLAUDE_CODE = truthy("PROJECTFLOWS_DISABLE_CLAUDE_CODE")
  export const PROJECTFLOWS_DISABLE_CLAUDE_CODE_PROMPT =
    PROJECTFLOWS_DISABLE_CLAUDE_CODE || truthy("PROJECTFLOWS_DISABLE_CLAUDE_CODE_PROMPT")
  export const PROJECTFLOWS_DISABLE_CLAUDE_CODE_SKILLS =
    PROJECTFLOWS_DISABLE_CLAUDE_CODE || truthy("PROJECTFLOWS_DISABLE_CLAUDE_CODE_SKILLS")
  export const PROJECTFLOWS_DISABLE_EXTERNAL_SKILLS =
    PROJECTFLOWS_DISABLE_CLAUDE_CODE_SKILLS || truthy("PROJECTFLOWS_DISABLE_EXTERNAL_SKILLS")
  export declare const PROJECTFLOWS_DISABLE_PROJECT_CONFIG: boolean
  export const PROJECTFLOWS_FAKE_VCS = process.env["PROJECTFLOWS_FAKE_VCS"]
  export declare const PROJECTFLOWS_CLIENT: string
  export const PROJECTFLOWS_SERVER_PASSWORD = process.env["PROJECTFLOWS_SERVER_PASSWORD"]
  export const PROJECTFLOWS_SERVER_USERNAME = process.env["PROJECTFLOWS_SERVER_USERNAME"]
  export const PROJECTFLOWS_ENABLE_QUESTION_TOOL = truthy("PROJECTFLOWS_ENABLE_QUESTION_TOOL")

  // Experimental
  export const PROJECTFLOWS_EXPERIMENTAL = truthy("PROJECTFLOWS_EXPERIMENTAL")
  export const PROJECTFLOWS_EXPERIMENTAL_FILEWATCHER = truthy("PROJECTFLOWS_EXPERIMENTAL_FILEWATCHER")
  export const PROJECTFLOWS_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("PROJECTFLOWS_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const PROJECTFLOWS_EXPERIMENTAL_ICON_DISCOVERY =
    PROJECTFLOWS_EXPERIMENTAL || truthy("PROJECTFLOWS_EXPERIMENTAL_ICON_DISCOVERY")

  const copy = process.env["PROJECTFLOWS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
  export const PROJECTFLOWS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT =
    copy === undefined ? process.platform === "win32" : truthy("PROJECTFLOWS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const PROJECTFLOWS_ENABLE_EXA =
    truthy("PROJECTFLOWS_ENABLE_EXA") || PROJECTFLOWS_EXPERIMENTAL || truthy("PROJECTFLOWS_EXPERIMENTAL_EXA")
  export const PROJECTFLOWS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("PROJECTFLOWS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const PROJECTFLOWS_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("PROJECTFLOWS_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const PROJECTFLOWS_EXPERIMENTAL_OXFMT = PROJECTFLOWS_EXPERIMENTAL || truthy("PROJECTFLOWS_EXPERIMENTAL_OXFMT")
  export const PROJECTFLOWS_EXPERIMENTAL_LSP_TY = truthy("PROJECTFLOWS_EXPERIMENTAL_LSP_TY")
  export const PROJECTFLOWS_EXPERIMENTAL_LSP_TOOL = PROJECTFLOWS_EXPERIMENTAL || truthy("PROJECTFLOWS_EXPERIMENTAL_LSP_TOOL")
  export const PROJECTFLOWS_DISABLE_FILETIME_CHECK = truthy("PROJECTFLOWS_DISABLE_FILETIME_CHECK")
  export const PROJECTFLOWS_EXPERIMENTAL_PLAN_MODE = PROJECTFLOWS_EXPERIMENTAL || truthy("PROJECTFLOWS_EXPERIMENTAL_PLAN_MODE")
  export const PROJECTFLOWS_EXPERIMENTAL_MARKDOWN = truthy("PROJECTFLOWS_EXPERIMENTAL_MARKDOWN")
  export const PROJECTFLOWS_MODELS_URL = process.env["PROJECTFLOWS_MODELS_URL"]
  export const PROJECTFLOWS_MODELS_PATH = process.env["PROJECTFLOWS_MODELS_PATH"]

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}

// Dynamic getter for PROJECTFLOWS_DISABLE_PROJECT_CONFIG
// evaluated at access time, not module load time
Object.defineProperty(Flag, "PROJECTFLOWS_DISABLE_PROJECT_CONFIG", {
  get() {
    return truthy("PROJECTFLOWS_DISABLE_PROJECT_CONFIG")
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for PROJECTFLOWS_TUI_CONFIG
Object.defineProperty(Flag, "PROJECTFLOWS_TUI_CONFIG", {
  get() {
    return process.env["PROJECTFLOWS_TUI_CONFIG"]
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for PROJECTFLOWS_CONFIG_DIR
Object.defineProperty(Flag, "PROJECTFLOWS_CONFIG_DIR", {
  get() {
    return process.env["PROJECTFLOWS_CONFIG_DIR"]
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for PROJECTFLOWS_CLIENT
Object.defineProperty(Flag, "PROJECTFLOWS_CLIENT", {
  get() {
    return process.env["PROJECTFLOWS_CLIENT"] ?? "cli"
  },
  enumerable: true,
  configurable: false,
})
