export type NodeType = 'start' | 'tool'

export type ExecutionMode = 'automatic' | 'manual'

export type JsonSchemaType =
  | 'string'
  | 'number'
  | 'integer'
  | 'boolean'
  | 'object'
  | 'array'
  | 'null'

export type ConditionOperator =
  | 'eq'
  | 'ne'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'contains'
  | 'startsWith'
  | 'endsWith'

export interface ExpressionReference {
  nodeId: string
  nodeName: string
  fieldName: string
  displayLabel?: string
}

export interface ParameterSchema {
  name: string
  type: JsonSchemaType
  description?: string
  required?: boolean
  default?: unknown
  enum?: unknown[]
  format?: string
  minLength?: number
  maxLength?: number
  pattern?: string
  minimum?: number
  maximum?: number
  exclusiveMinimum?: number
  exclusiveMaximum?: number
  multipleOf?: number
  minItems?: number
  maxItems?: number
  uniqueItems?: boolean
  items?: ParameterSchema
  minProperties?: number
  maxProperties?: number
  properties?: Record<string, ParameterSchema>
  additionalProperties?: boolean | ParameterSchema
  title?: string
  readOnly?: boolean
  writeOnly?: boolean
  deprecated?: boolean
  valueMode?: 'static' | 'expression'
  expression?: ExpressionReference
  fromActionNode?: boolean
  originalActionNodeId?: string
}

export interface OutputSchema {
  type: JsonSchemaType
  description?: string
  enum?: unknown[]
  format?: string
  minLength?: number
  maxLength?: number
  pattern?: string
  minimum?: number
  maximum?: number
  exclusiveMinimum?: number
  exclusiveMaximum?: number
  multipleOf?: number
  minItems?: number
  maxItems?: number
  uniqueItems?: boolean
  items?: OutputSchema
  minProperties?: number
  maxProperties?: number
  properties?: Record<string, OutputSchema>
  additionalProperties?: boolean | OutputSchema
  title?: string
  readOnly?: boolean
  writeOnly?: boolean
  deprecated?: boolean
}

export interface ToolAnnotations {
  title?: string
  audience?: 'agent' | 'user'
  priority?: 'normal' | 'high' | 'low'
  destructiveHint?: boolean
  idempotentHint?: boolean
  openWorldHint?: boolean
  readOnlyHint?: boolean
}

export interface EdgeCondition {
  field: string
  operator: ConditionOperator
  value: unknown
  description?: string
  targetHandle?: string
}

export interface OutputFieldSelection {
  fieldName: string
  required: boolean
  description?: string
  defaultValue?: unknown
  autoGenerated?: boolean
}

export interface InputMapping {
  sourceField: string
  targetField: string
  transform?: string
  required?: boolean
}

export interface NodeProperties {
  label: string
  name?: string
  description?: string
  execution_mode?: ExecutionMode
  execution_mode_override?: ExecutionMode
  status?: 'draft' | 'published' | 'archived'
  action_id?: string
  parameters?: Record<string, unknown>
}

export interface NodeDataConfig {
  inputs: ParameterSchema[]
  outputs: ParameterSchema[]
}

export interface UnifiedNodeData extends Record<string, unknown> {
  nodeType?: NodeType
  node: NodeProperties
  data: NodeDataConfig
  conditions?: EdgeCondition[]
  annotations?: ToolAnnotations
  toolAnnotations?: ToolAnnotations
  instructions?: string
  output_field_selection?: OutputFieldSelection[]
  input_mapping?: InputMapping[]
  stage_id?: string
  next_stage_id?: string
}

export type WorkflowNodeData = UnifiedNodeData
